# Generated by Django 6.0.3 on 2026-04-17 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
